config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#root'
  
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord


    attr_reader :password
    validates :username, :session_token, :password_digest, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }
    after_initialize :ensure_session_token
  
  
    def self.find_by_credentials(user_params)
      user = User.find_by(username: user_params[:username])
      user && user.is_password?(user_params[:password]) ? user : nil
    end
  
    def ensure_session_token
      self.session_token = SecureRandom::urlsafe_base64
    end
  
    def is_password?(password)
      BCrypt::Password.new(self.password_digest).is_password?(password)
    end
  
    def password=(password)
      @password = password
      self.password_digest = BCrypt::Password.create(password)
    end
  
    def reset_session_token!
      update!(session_token: SecureRandom::urlsafe_base64)
      session_token
    end
    
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?
  
    private
    def current_user
      @current_user ||= User.find_by(session_token: session[:session_token])
    end
  
    def logged_in?
      !!current_user
    end
  
    def login!(user)
      session[:session_token] = user.reset_session_token!
      @current_user = user
    end
  
    def logout!
      current_user.try(:reset_session_token!)
      session[:session_token] = nil
    end
  
    def redirect_if_logged_in
     redirect_to root_url if logged_in?
    end
  
    def redirect_if_not_logged_in
      redirect_to new_session_url unless logged_in?
    end
  
    def deny_access_if_not_logged_in
      unless logged_in?
        render json: ['You must be logged in to do that'], status: :unauthorized
      end
    end
  
    def user_params
      params.require(:user).permit(:username, :password)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :redirect_if_logged_in, except: :destroy

    def new
      @user = User.new
    end
  
    def create
      @user = User.find_by_credentials(user_params)
      if @user
        login!(@user)
        redirect_to root_url
      else
        @user = User.new
        flash.now[:errors] = { base: ['Invalid username or password'] }
        render :new
      end
    end
  
    def destroy
      logout!
      redirect_to new_session_url
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def root
        if !logged_in?
            redirect_to new_session_url
        end

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :redirect_if_logged_in

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors
      render :new
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SBHackApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Barlow|Lobster|Bebas+Neue&display=swap" rel="stylesheet">
    

  </head>

  <body>
    <header class = "header">
      <nav class = "header-nav">
        <h1 class = "nav-logo"> 2Nite </h1>
        <% if logged_in? %>
          <form action="<%= session_url %>" method="post" class="l">
          <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <button class = "log-out"><input type="submit">Log Out</button>
        </form>
        <% end %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/static _pages/root.html.erb
<div id="content">
</div>

app/views/shared/_errors.html.erb
<% if errors && errors[type] %>
  <ul>
    <% errors[type].each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_user_form.html.erb
<form action="<%= action %>" method="POST">
  <%= render "shared/errors", errors: flash[:errors], type: :base %>
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >
  <%#<label for="username-input">Username</label> %>
  <input
    id="username-input"
    type="text"
    name="user[username]"
    value="<%= user.username %>"
    placeholder= "Username"
  >
    <%= render 'shared/errors', errors: flash[:errors], type: :username %>
  <%#<label for="password-input">Password</label> %>
  <input
    type="password"
    name="user[password]"
    id="password-input"
    placeholder = "Password"
  >
    <%= render 'shared/errors', errors: flash[:errors], type: :password %>

  
  <button class="button first-button"><%= submit_text %></button>


  <p>or</p>



  <% if submit_text === "Sign Up" %>

    <%= link_to '<button type="button" class = "button second-button">Sign In</button>'.html_safe, new_session_url %>

  <% else %>

    <%= link_to '<button type="button" class = "button second-button">Sign Up</button>'.html_safe, new_user_url %>
  
  <%end %>
  
</form>

app/views/static_pages/root.html.erb
<div id="content">

</div>

app/views/users/new.html.erb
 
<div class="splash-content">
<h1>2Nite</h1>

<h3>Sign Up</h3>

<%= render 'shared/user_form', user: @user, submit_text: 'Sign Up', action: users_url %>
<!--<button class = "button" <a href="<%= new_session_url %>">Sign In</a></buton>-->
</div>

app/views/users/show.html.erb
<div id = "content">
</div>